# Generated by Django 6.1.1 on 2026-10-04 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Género',
                'verbose_name_plural': 'Géneros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('sinopsis', models.TextField(verbose_name='Sinopsis')),
                ('anio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('duracion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Duración en minutos')),
                ('imagen', models.URLField(blank=True, verbose_name='URL del póster')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('generos', models.ManyToManyField(related_name='peliculas', to='peliculas.genero', verbose_name='Géneros')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['titulo'],
            },
        ),
    ]
